version: '3'
services:
  mongoDB:
    image: "bitnami/mongodb:latest"
    ports:
      - 27017:27017
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    #    environment:
    #      POSTGRES_USER: unicorn_user
    #      POSTGRES_PASSWORD: magical_password
    #      POSTGRES_DB: rainbow_database
    #    env_file:
    #      - database.env # configure postgres
    expose:
      - 5432
    ports:
      - 5432:5432
  #    volumes:
  #      - ./db/dev/databases.sql:/docker-entrypoint-initdb.d/1-dev-database.sql
  #      - ./db/dev/roles.sql:/docker-entrypoint-initdb.d/2-dev-roles.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1